services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Dockerfile # path to your backend Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        value: https://jqlixwmobrcnidxvwawe.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_xalz3oXVy39ie-A1bJZFRw_-B6dW4SO
      - key: REDIS_URL
        value: redis://redis:6379
      - key: PORT
        value: 3000

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    autoDeploy: true
    envVars: []

  - type: redis
    name: redis
    plan: free
    maxmemoryPolicy: allkeys-lru
